# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.srcs/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/design_1_PmodCOLOR_0_0.xci
# IP: The module: 'design_1_PmodCOLOR_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlslice_0_0/PmodCOLOR_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_0 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlslice_0_1/PmodCOLOR_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_1 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_1} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlslice_0_2/PmodCOLOR_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_2 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_2} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlconcat_0_0/PmodCOLOR_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_0 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlconcat_0_1/PmodCOLOR_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_1 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_1} -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_ooc.xdc

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/design_1_PmodCOLOR_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCOLOR_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCOLOR_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_ooc.xdc

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.srcs/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/design_1_PmodCOLOR_0_0.xci
# IP: The module: 'design_1_PmodCOLOR_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlslice_0_0/PmodCOLOR_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_0 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlslice_0_1/PmodCOLOR_xlslice_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_1 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_1} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlslice_0_2/PmodCOLOR_xlslice_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_2 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_2} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlconcat_0_0/PmodCOLOR_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_0 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_0} -quiet] -quiet

# IP: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_xlconcat_0_1/PmodCOLOR_xlconcat_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_1 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_1} -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_ooc.xdc

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/design_1_PmodCOLOR_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCOLOR_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodCOLOR_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_ooc.xdc

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/angel/ECE520L/final_project/hardware/PMOD_Color/PMOD_Color.gen/sources_1/bd/design_1/ip/design_1_PmodCOLOR_0_0/src/PmodCOLOR_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
